kind: pipeline
type: docker
name: default

steps:
  - name: hello-world
    image: alpine

    commands:
      - echo "Drone CI is working"
      - date
      - hostname
      - echo "Second build"
      - echo "third build"
